version: "3.8"
services:
  app:
    build:
      context: .
      target: builder
    command: sh -c "mix ecto.create; mix ecto.migrate; mix phx.server"
    ports:
      - "4000:4000"
    environment:
      PG_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

